name: hello
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6

  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  firebase_core: ^0.4.2 # add dependency for Firebase Core
  firebase_database: ^3.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #cloud_firestore: ^0.13.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: DoHyeon
      fonts:
        - asset: fonts/DoHyeon-Regular.ttf
